### PR TITLE
Fix .gitignore for MOE

### PR DESCRIPTION
**Pull request by Berstanio**

### CODE REVIEW

**Comment by Frosty-J** [comment]
Shouldn't iOS MOE gitignore be in addition to iOS rather than instead of? But I don't do iOS development, so ¯\\\_(ツ)_/¯

**Comment by Berstanio** [comment]
The excludes are moe exclusive. mobiVM doesn't have a xcode project

**Comment by tommyettinger** [comment]
I'm not so sure on this, because gdx-setup excludes the same iOS-related files that Liftoff does currently: https://github.com/libgdx/libgdx/blob/master/extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/gitignore#L108-L114

I'm open to adding the ios-moe excludes, but I don't want to un-exclude something that gdx-setup does currently exclude, presumably for a good reason.

**Comment by Berstanio** [comment]
The excludes on gdx-setup are just a artifact when MOE was a official backend. It probably just wasn't removed when the moe backend got removed. The mobiVM doesn't have a xcode project at all, therefor the exclude don't make sense. The mobiVM excludes on gdx-setup are the following: https://github.com/libgdx/libgdx/blob/f68e6359673797399db62273c7bea150407aa7be/extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/gitignore#L8-L9

However I'm not 100% sure about 
/ios/IOSLauncher.app
/ios/IOSLauncher.app.dSYM
 They shouldn't be related to mobiVM, but I will just double them to be safe.

**Review by tommyettinger — APPROVED** [review]
I'll delegate to your MOE expertise here, since I don't have much of a clue when it comes to libGDX and iOS. This seems like it should be stable as long as RoboVM doesn't use XCode for anything. Maybe it did in the past? Anyway, I'll merge this, and if problems show up, it will be an easy fix.

**Pull request merged**
