### PR TITLE
html-gwt build.gradle file update

### LINKED ISSUE #14: Default build does not work for 'html' module
When running a just created liftoff project and running `html:superDev` results in the exception below. 

```
Task :html:draftCompileGwt FAILED
Loading inherited module 'com.virtual_hex.games.freeuniverse.GdxDefinitionSuperdev'
   Loading inherited module 'com.virtual_hex.games.freeuniverse.GdxDefinition'
      Loading inherited module 'com.virtual_hex.games.freeuniverse.Shared'
         [ERROR] Unable to find 'com/virtual_hex/games/freeuniverse/Shared.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
```

The resolution is to update this block
```
task addSource {
    doLast {
        sourceSets.main.compileClasspath += files(project(':core').sourceSets.main.allJava.srcDirs)
        sourceSets.main.compileClasspath += files(project(':shared').sourceSets.main.allJava.srcDirs)
    }
}
```

 in the `html` modules `build.gradle`.

### PR DESCRIPTION
**Pull request by Mr00Anderson**
Closes #14 
+ `sourceSets.main.compileClasspath += files(project(':shared').sourceSets.main.allJava.srcDirs)`
- Application rebuilt, generated new project and ran correctly.

### CODE REVIEW

**Comment by Mr00Anderson** [comment]
Yea- I forgot about editing the title ahead of time since its wonky though the ide.

**Comment by Mr00Anderson** [comment]
By the way the previous way to solve this in older gradle was to add 
```
    compile project(":shared")
    compile project(path: ':shared', configuration: 'compile')
```
in `build.gradle` in the `core` module. This would automatically cause the inheritance to follow through into the next `build.gradle` so that in `html` module when it adds a dependency like this 
```
    compile project(":core")
    compile project(path: ':core', configuration: 'compile')
```
it would automatically pick up the `shared` module and its dependencies from its `build.gradle`

**Comment by tommyettinger** [comment]
Thanks, looking through this. I haven't checked what #14 is yet, will do so in a bit.

I think you have `api` and `implementation` backwards; `api` I'm pretty sure makes transitive dependencies visible to code that uses that, well, API, while `implementation` allows some kind of hiding of transitive dependencies, maybe only when tools do so (like ProGuard). I don't know the specifics; `api` is meant for libraries and requires the `java-library` plugin. I'm pretty sure `compile` works at the moment with Gradle 6.x, but is very much deprecated and the Gradle devs want it removed in 7.x.

**Comment by tommyettinger** [comment]
OK, this PR would break all projects with an `html` module and no `shared` module... If the `:shared` module isn't in the project, referencing it is a build-time error. Solving this is going to need some extra work, and I wonder if `shared` would also need to be added to the source sets for other modules (`android`, `lwjgl3`, etc.).

**Comment by tommyettinger** [comment]
The fix was pretty simple; one line to add an if/else. I checked this in HTML projects with and without shared, and it seems to work. Thanks, @Mr00Anderson !

**Pull request merged**
